services:
  db: 
    image: postgres
    volumes: 
      - ./data/db:/var/lib/pgsql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=123qwe!@#QWE
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD=123qwe!@#QWE
    links:
      - "db:db"

  