# Generated by Django 4.1.7 on 2023-03-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to='client-photo/'),
        ),
    ]
