# Generated by Django 4.1.7 on 2023-03-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0002_alter_photo_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_photo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client_API.photo'),
        ),
    ]
