# Generated by Django 4.1.7 on 2023-03-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0003_alter_client_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client_API.photo'),
        ),
    ]
