# Generated by Django 4.1.7 on 2023-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0004_alter_client_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.JSONField(null=True),
        ),
    ]
