# Generated by Django 4.1.7 on 2023-03-15 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_API', '0005_client_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='message',
        ),
        migrations.AddField(
            model_name='client',
            name='client_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
